#!/usr/bin/env python3
"""
Generate SQL to update F2L recognition groups in Supabase.

Reads the local F2L JSON and generates SQL UPDATE statements
that can be executed via Supabase MCP.
"""

import json
from pathlib import Path

# Path to F2L cases JSON
F2L_JSON_PATH = Path(__file__).parent.parent.parent / "Deddal/Data/Resources/SeedData/3x3_cfop_f2l_cases.json"
OUTPUT_SQL_PATH = Path(__file__).parent / "f2l_groups_update.sql"

def escape_sql_array(groups):
    """Convert Python list to PostgreSQL ARRAY literal."""
    # Escape single quotes in strings
    escaped = ["'" + g.replace("'", "''") + "'" for g in groups]
    return "ARRAY[" + ", ".join(escaped) + "]"

def generate_sql():
    """Generate SQL UPDATE statements for all F2L cases."""

    print("=" * 80)
    print("Generate SQL to Update F2L Recognition Groups")
    print("=" * 80)

    # Load F2L JSON
    print(f"\nLoading F2L cases from: {F2L_JSON_PATH}")
    with open(F2L_JSON_PATH, 'r') as f:
        f2l_cases = json.load(f)

    print(f"  Loaded {len(f2l_cases)} F2L cases")

    # Generate SQL
    sql_statements = []
    sql_statements.append("-- Update F2L recognition groups")
    sql_statements.append("-- Generated by: generate_f2l_update_sql.py")
    sql_statements.append("-- All 82 F2L cases with 7-category recognition system\n")

    for case in f2l_cases:
        code = case['code']
        groups = case.get('groups', [])

        array_literal = escape_sql_array(groups)

        sql = f"UPDATE lib_cases SET groups = {array_literal} WHERE code = '{code}';"
        sql_statements.append(sql)

    # Add verification query at the end
    sql_statements.append("\n-- Verify updates")
    sql_statements.append("SELECT code, array_length(groups, 1) as group_count")
    sql_statements.append("FROM lib_cases")
    sql_statements.append("WHERE code LIKE 'F2L-%'")
    sql_statements.append("ORDER BY code;")

    # Write to file
    sql_content = "\n".join(sql_statements)

    with open(OUTPUT_SQL_PATH, 'w') as f:
        f.write(sql_content)

    print(f"\n✅ Generated SQL file: {OUTPUT_SQL_PATH}")
    print(f"   Total UPDATE statements: {len(f2l_cases)}")
    print(f"\nTo execute, use Supabase MCP:")
    print(f"  mcp__supabase__execute_sql with the contents of {OUTPUT_SQL_PATH.name}")
    print("=" * 80)

if __name__ == "__main__":
    generate_sql()
