#!/usr/bin/env python3
"""
Update beginner_cases.json and beginner_algorithms.json with new UUIDs.
Uses the mapping generated by generate_uuids.py.
"""

import json

# Paths
MAPPING_FILE = "/Users/trophee-mini/code/deddal/deddal-ios/uuid_mapping.json"
CASES_FILE = "/Users/trophee-mini/code/deddal/deddal-ios/Deddal/Data/Resources/SeedData/beginner_cases.json"
ALGORITHMS_FILE = "/Users/trophee-mini/code/deddal/deddal-ios/Deddal/Data/Resources/SeedData/beginner_algorithms.json"

def main():
    # Load UUID mappings
    with open(MAPPING_FILE, "r") as f:
        mappings = json.load(f)

    case_mapping = mappings["case_mapping"]
    algorithm_mapping = mappings["algorithm_mapping"]

    print("Updating beginner_cases.json...")
    print("="*60)

    # Update cases
    with open(CASES_FILE, "r") as f:
        cases = json.load(f)

    updated_cases_count = 0
    for case in cases:
        old_id = case["id"]
        if old_id in case_mapping:
            new_id = case_mapping[old_id]
            case["id"] = new_id
            updated_cases_count += 1
            print(f"✓ {old_id:20} -> {new_id}")
        else:
            print(f"⚠ Skipped (not in mapping): {old_id}")

    # Save updated cases
    with open(CASES_FILE, "w") as f:
        json.dump(cases, f, indent=2)

    print(f"\n✅ Updated {updated_cases_count}/{len(cases)} cases")
    print("="*60)
    print("\nUpdating beginner_algorithms.json...")
    print("="*60)

    # Update algorithms
    with open(ALGORITHMS_FILE, "r") as f:
        algorithms = json.load(f)

    updated_algs_count = 0
    updated_case_refs = 0
    for alg in algorithms:
        old_alg_id = alg["id"]
        old_case_id = alg["case_id"]

        # Update algorithm ID
        if old_alg_id in algorithm_mapping:
            new_alg_id = algorithm_mapping[old_alg_id]
            alg["id"] = new_alg_id
            updated_algs_count += 1
        else:
            print(f"⚠ Algorithm ID not in mapping: {old_alg_id}")
            new_alg_id = old_alg_id

        # Update case_id reference
        if old_case_id in case_mapping:
            new_case_id = case_mapping[old_case_id]
            alg["case_id"] = new_case_id
            updated_case_refs += 1
            print(f"✓ {old_alg_id:20} -> {new_alg_id}")
            print(f"  └─ case_id: {old_case_id:15} -> {new_case_id}")
        else:
            print(f"⚠ Case ID not in mapping: {old_case_id}")

    # Save updated algorithms
    with open(ALGORITHMS_FILE, "w") as f:
        json.dump(algorithms, f, indent=2)

    print(f"\n✅ Updated {updated_algs_count}/{len(algorithms)} algorithm IDs")
    print(f"✅ Updated {updated_case_refs}/{len(algorithms)} case_id references")
    print("="*60)
    print("\n🎉 All JSON files updated successfully!")

if __name__ == "__main__":
    main()
