#!/usr/bin/env python3
"""
Fix OELL (Edge OLL) setupSequence (scramble) values.
The scramble values were incorrectly set to algorithms instead of setup moves.

Setup sequences are the inverse of the algorithms - they transform
"Top Edges Oriented" into the case state (misoriented edges).

Algorithms from Speedsolving Wiki:
- L-shape: f R U R' U' f'
- Line: F R U R' U' F'
- Dot: F R U R' U' F' f R U R' U' f'
"""

import json
import os

# Correct setup sequences (inverses of algorithms)
OELL_SETUP_SEQUENCES = {
    "OeLL L": "f U R U' R' f'",           # Inverse of: f R U R' U' f'
    "OeLL Line": "F U R U' R' F'",        # Inverse of: F R U R' U' F'
    "OeLL Dot": "f U R U' R' f' F U R U' R' F'",  # Inverse of: F R U R' U' F' f R U R' U' f'
}


def update_json_file(json_path: str) -> int:
    """Update the JSON seed file with correct setup sequences."""
    with open(json_path, 'r') as f:
        cases = json.load(f)

    updated_count = 0
    for case in cases:
        code = case.get('code')
        if code in OELL_SETUP_SEQUENCES:
            old_scramble = case.get('scramble', '')
            new_scramble = OELL_SETUP_SEQUENCES[code]

            if old_scramble != new_scramble:
                print(f"Updating {code}:")
                print(f"  OLD: {old_scramble}")
                print(f"  NEW: {new_scramble}")
                case['scramble'] = new_scramble
                updated_count += 1

    # Write back to JSON
    with open(json_path, 'w') as f:
        json.dump(cases, f, indent=2)

    return updated_count


def generate_sql_migration(output_path: str):
    """Generate SQL migration file for Supabase."""
    sql_lines = [
        "-- Fix OELL setupSequence (scramble) values",
        "-- The scramble values were incorrectly set to algorithms instead of setup moves",
        "-- Generated by fix_oell_setup_sequences.py",
        "",
        "BEGIN;",
        ""
    ]

    for code, setup in OELL_SETUP_SEQUENCES.items():
        # Escape single quotes for SQL
        escaped_setup = setup.replace("'", "''")
        sql_lines.append(f"UPDATE lib_cases SET scramble = '{escaped_setup}' WHERE code = '{code}';")

    sql_lines.extend([
        "",
        "COMMIT;",
        ""
    ])

    with open(output_path, 'w') as f:
        f.write('\n'.join(sql_lines))


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(os.path.dirname(script_dir))

    # Update JSON seed file
    json_path = os.path.join(project_root, 'Deddal', 'Data', 'Resources', 'SeedData', '3x3_cfop_oell_cases.json')

    print("=" * 60)
    print("OELL Setup Sequence Fix")
    print("=" * 60)
    print()

    if os.path.exists(json_path):
        print(f"Updating JSON: {json_path}")
        updated = update_json_file(json_path)
        print(f"\nUpdated {updated} cases in JSON")
    else:
        print(f"JSON file not found: {json_path}")

    # Generate SQL migration
    sql_path = os.path.join(script_dir, 'fix_oell_setup_sequences.sql')
    print(f"\nGenerating SQL: {sql_path}")
    generate_sql_migration(sql_path)
    print("SQL migration generated")

    print()
    print("=" * 60)
    print("Done!")
    print("=" * 60)
    print()
    print("Next steps:")
    print("1. Review the changes in the JSON file")
    print("2. Apply the SQL migration to Supabase")


if __name__ == "__main__":
    main()
