#!/usr/bin/env python3
"""
Fix PLL setupSequence (scramble) values.
The scramble values were incorrectly set to algorithms instead of setup moves.

Setup sequences from SpeedCubeDB - these transform solved state into the case state.
"""

import json
import os

# Correct setup sequences from SpeedCubeDB
# These transform the solved cube into the PLL case state
PLL_SETUP_SEQUENCES = {
    "Aa-Perm": "x R2' D2' R U R' D2' R U' R x'",
    "Ab-Perm": "x R' U R' D2' R U' R' D2' R2' x'",
    "E-Perm": "x' D R U R' D' R U' R' D R U' R' D' R U R' x y'",
    "F-Perm": "R' U' R U' R' U R U R2' F' R U R U' R' F U R y'",
    "Ga-Perm": "R' U' R D' U R2' U R' U R U' R U' R2' D",
    "Gb-Perm": "R2' U R' U R' U' R U' R2' D U' R' U R D'",
    "Gc-Perm": "D' R U R' U' D R2' U' R U' R' U R' U R2'",
    "Gd-Perm": "R2' U' R U' R U R' U R2' D' U R U' R' D",
    "H-Perm": "M2' U' M2' U2' M2' U' M2'",
    "Ja-Perm": "L' R' U2' R U R' U2' L U' R y'",
    "Jb-Perm": "R U R2' F' R U R U' R' F R U' R'",
    "Na-Perm": "R U R' U2' R U R2' F' R U R U' R' F R U' R' U' R U' R'",
    "Nb-Perm": "F r' F' r U r U' r2' D' F r U r' F' D r",
    "Ra-Perm": "R U2' R D R' U R D' R' U' R' U R U R' y'",
    "Rb-Perm": "R' U R U R' U' R' D' R U R' D R U2' R",
    "T-Perm": "F R U' R' U R U R2' F' R U R U' R'",
    "Ua-Perm": "M2' U' M' U2' M U' M2'",
    "Ub-Perm": "M2' U M' U2' M U M2'",
    "V-Perm": "D2' R' U R D' R2' U' R' U R' U R' D' R U2' R'",
    "Y-Perm": "F R' F' R U R U' R' F R U' R' U R U R' F'",
    "Z-Perm": "M U2' M2' U2' M U' M2' U' M2'",
}


def update_json_file(json_path: str) -> int:
    """Update the JSON seed file with correct setup sequences."""
    with open(json_path, 'r') as f:
        cases = json.load(f)

    updated_count = 0
    for case in cases:
        code = case.get('code')
        if code in PLL_SETUP_SEQUENCES:
            old_scramble = case.get('scramble', '')
            new_scramble = PLL_SETUP_SEQUENCES[code]

            if old_scramble != new_scramble:
                print(f"Updating {code}:")
                print(f"  OLD: {old_scramble}")
                print(f"  NEW: {new_scramble}")
                case['scramble'] = new_scramble
                updated_count += 1

    # Write back to JSON
    with open(json_path, 'w') as f:
        json.dump(cases, f, indent=2)

    return updated_count


def generate_sql_migration(output_path: str):
    """Generate SQL migration file for Supabase."""
    sql_lines = [
        "-- Fix PLL setupSequence (scramble) values",
        "-- The scramble values were incorrectly set to algorithms instead of setup moves",
        "-- Generated by fix_pll_setup_sequences.py",
        "",
        "BEGIN;",
        ""
    ]

    for code, setup in PLL_SETUP_SEQUENCES.items():
        # Escape single quotes for SQL
        escaped_setup = setup.replace("'", "''")
        sql_lines.append(f"UPDATE lib_cases SET scramble = '{escaped_setup}' WHERE code = '{code}';")

    sql_lines.extend([
        "",
        "COMMIT;",
        ""
    ])

    with open(output_path, 'w') as f:
        f.write('\n'.join(sql_lines))


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(os.path.dirname(script_dir))

    # Update JSON seed file
    json_path = os.path.join(project_root, 'Deddal', 'Data', 'Resources', 'SeedData', '3x3_cfop_pll_cases.json')

    print("=" * 60)
    print("PLL Setup Sequence Fix")
    print("=" * 60)
    print()

    if os.path.exists(json_path):
        print(f"Updating JSON: {json_path}")
        updated = update_json_file(json_path)
        print(f"\nUpdated {updated} cases in JSON")
    else:
        print(f"JSON file not found: {json_path}")

    # Generate SQL migration
    sql_path = os.path.join(script_dir, 'fix_pll_setup_sequences.sql')
    print(f"\nGenerating SQL: {sql_path}")
    generate_sql_migration(sql_path)
    print("SQL migration generated")

    print()
    print("=" * 60)
    print("Done!")
    print("=" * 60)
    print()
    print("Next steps:")
    print("1. Review the changes in the JSON file")
    print("2. Apply the SQL migration to Supabase")


if __name__ == "__main__":
    main()
