#!/usr/bin/env python3
"""
Fix OLL setupSequence (scramble) values.
The scramble values were incorrectly set to algorithms instead of setup moves.

Setup sequences from SpeedCubeDB - these transform solved state into the case state.
"""

import json
import os

# Correct setup sequences from SpeedCubeDB
# These transform the solved cube into the OLL case state
OLL_SETUP_SEQUENCES = {
    "OLL-1": "F R' F' R U2' F R' F' R2' U2' R'",
    "OLL-2": "f U R U' R' f' F U R U' R' F'",
    "OLL-3": "F U R U' R' F' U f U R U' R' f' y",
    "OLL-4": "F U R U' R' F' U' f U R U' R' f' y",
    "OLL-5": "r' U' R U' R' U2' r",
    "OLL-6": "r U R' U R U2' r'",
    "OLL-7": "r U2' R' U' R U' r'",
    "OLL-8": "r' U2' R U R' U r y2'",
    "OLL-9": "F U R U' R2' F' R U R U' R' y'",
    "OLL-10": "R U2' R' F R' F' R U' R U' R'",
    "OLL-11": "M U' R U2' R' U' R U' R2' r",
    "OLL-12": "F U R U' R' F' U' F U R U' R' F'",
    "OLL-13": "F' U' F r U' r' U r U r'",
    "OLL-14": "F U F' R' F R U' R' F' R",
    "OLL-15": "r' U' r U' R' U R r' U r",
    "OLL-16": "r U r' U R U' R' r U' r'",
    "OLL-17": "F R' F' R U2' F R' F' R U' R U' R'",
    "OLL-18": "r' U2' R U R' U r2' U2' R' U' R U' r'",
    "OLL-19": "F R' F' R M U R U' R' U' M'",
    "OLL-20": "r U R' U' M2' U R U' R' U' M'",
    "OLL-21": "R U R' U R U' R' U R U2' R' y'",
    "OLL-22": "R' U2' R2' U R2' U R2' U2' R'",
    "OLL-23": "R U2' R D R' U2' R D' R2'",
    "OLL-24": "F R' F' r U R U' r'",
    "OLL-25": "R' F' r U R U' r' F y'",
    "OLL-26": "R U R' U R U2' R' y'",
    "OLL-27": "R U2' R' U' R U' R'",
    "OLL-28": "R U R' U' M' U R U' r'",
    "OLL-29": "M F R' F' R U R U' R' U' M'",
    "OLL-30": "F U R U2' R' U R U2' R' U' F' y2'",
    "OLL-31": "R' F R U R' U' F' U R",
    "OLL-32": "f R' F' R U R U' R' S'",
    "OLL-33": "F R' F' R U R U' R'",
    "OLL-34": "F U R' U' R' F' R U R2' U' R' y2'",
    "OLL-35": "R U2' R' F R' F' R2' U2' R'",
    "OLL-36": "F' L F L' U' L' U' L U L' U L y2'",
    "OLL-37": "F R U' R' U R U R' F'",
    "OLL-38": "F R' F' R U R U R' U' R U' R'",
    "OLL-39": "L U F' U' L' U L F L' y'",
    "OLL-40": "R' U' F U R U' R' F' R y'",
    "OLL-41": "F U R U' R' F' R U2' R' U' R U' R' y2'",
    "OLL-42": "F U R U' R' F' R' U2' R U R' U R",
    "OLL-43": "f' U' L' U L f",
    "OLL-44": "f U R U' R' f'",
    "OLL-45": "F U R U' R' F'",
    "OLL-46": "R' U' F R' F' R U R",
    "OLL-47": "F' U' L' U L U' L' U L F",
    "OLL-48": "F U R U' R' U R U' R' F'",
    "OLL-49": "r' U r2' U' r2' U' r2' U r' y2'",
    "OLL-50": "r U' r2' U r2' U r2' U' r",
    "OLL-51": "f U R U' R' U R U' R' f'",
    "OLL-52": "F R U R' d R' U' R U' R'",
    "OLL-53": "r' U2' R U R' U' R U R' U r",
    "OLL-54": "r U2' R' U' R U R' U' R U' r'",
    "OLL-55": "F R' F' U2' R U R' U R2' U2' R'",
    "OLL-56": "r U r' R U R' U' R U R' U' r U' r'",
    "OLL-57": "r U R' U' M U R U' R'",
}


def update_json_file(json_path: str) -> int:
    """Update the JSON seed file with correct setup sequences."""
    with open(json_path, 'r') as f:
        cases = json.load(f)

    updated_count = 0
    for case in cases:
        code = case.get('code')
        if code in OLL_SETUP_SEQUENCES:
            old_scramble = case.get('scramble', '')
            new_scramble = OLL_SETUP_SEQUENCES[code]

            if old_scramble != new_scramble:
                print(f"Updating {code}:")
                print(f"  OLD: {old_scramble[:60]}...")
                print(f"  NEW: {new_scramble}")
                case['scramble'] = new_scramble
                updated_count += 1

    # Write back to JSON
    with open(json_path, 'w') as f:
        json.dump(cases, f, indent=2)

    return updated_count


def generate_sql_migration(output_path: str):
    """Generate SQL migration file for Supabase."""
    sql_lines = [
        "-- Fix OLL setupSequence (scramble) values",
        "-- The scramble values were incorrectly set to algorithms instead of setup moves",
        "-- Generated by fix_oll_setup_sequences.py",
        "",
        "BEGIN;",
        ""
    ]

    for code, setup in OLL_SETUP_SEQUENCES.items():
        # Escape single quotes for SQL
        escaped_setup = setup.replace("'", "''")
        sql_lines.append(f"UPDATE lib_cases SET scramble = '{escaped_setup}' WHERE code = '{code}';")

    sql_lines.extend([
        "",
        "COMMIT;",
        ""
    ])

    with open(output_path, 'w') as f:
        f.write('\n'.join(sql_lines))


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(os.path.dirname(script_dir))

    # Update JSON seed file
    json_path = os.path.join(project_root, 'Deddal', 'Data', 'Resources', 'SeedData', '3x3_cfop_oll_cases.json')

    print("=" * 60)
    print("OLL Setup Sequence Fix")
    print("=" * 60)
    print()

    if os.path.exists(json_path):
        print(f"Updating JSON: {json_path}")
        updated = update_json_file(json_path)
        print(f"\nUpdated {updated} cases in JSON")
    else:
        print(f"JSON file not found: {json_path}")

    # Generate SQL migration
    sql_path = os.path.join(script_dir, 'fix_oll_setup_sequences.sql')
    print(f"\nGenerating SQL: {sql_path}")
    generate_sql_migration(sql_path)
    print("SQL migration generated")

    print()
    print("=" * 60)
    print("Done!")
    print("=" * 60)
    print()
    print("Next steps:")
    print("1. Review the changes in the JSON file")
    print("2. Apply the SQL migration to Supabase")


if __name__ == "__main__":
    main()
