-- Fix PLL setupSequence (scramble) values
-- The scramble values were incorrectly set to algorithms instead of setup moves
-- Generated by fix_pll_setup_sequences.py

BEGIN;

UPDATE lib_cases SET scramble = 'x R2'' D2'' R U R'' D2'' R U'' R x''' WHERE code = 'Aa-Perm';
UPDATE lib_cases SET scramble = 'x R'' U R'' D2'' R U'' R'' D2'' R2'' x''' WHERE code = 'Ab-Perm';
UPDATE lib_cases SET scramble = 'x'' D R U R'' D'' R U'' R'' D R U'' R'' D'' R U R'' x y''' WHERE code = 'E-Perm';
UPDATE lib_cases SET scramble = 'R'' U'' R U'' R'' U R U R2'' F'' R U R U'' R'' F U R y''' WHERE code = 'F-Perm';
UPDATE lib_cases SET scramble = 'R'' U'' R D'' U R2'' U R'' U R U'' R U'' R2'' D' WHERE code = 'Ga-Perm';
UPDATE lib_cases SET scramble = 'R2'' U R'' U R'' U'' R U'' R2'' D U'' R'' U R D''' WHERE code = 'Gb-Perm';
UPDATE lib_cases SET scramble = 'D'' R U R'' U'' D R2'' U'' R U'' R'' U R'' U R2''' WHERE code = 'Gc-Perm';
UPDATE lib_cases SET scramble = 'R2'' U'' R U'' R U R'' U R2'' D'' U R U'' R'' D' WHERE code = 'Gd-Perm';
UPDATE lib_cases SET scramble = 'M2'' U'' M2'' U2'' M2'' U'' M2''' WHERE code = 'H-Perm';
UPDATE lib_cases SET scramble = 'L'' R'' U2'' R U R'' U2'' L U'' R y''' WHERE code = 'Ja-Perm';
UPDATE lib_cases SET scramble = 'R U R2'' F'' R U R U'' R'' F R U'' R''' WHERE code = 'Jb-Perm';
UPDATE lib_cases SET scramble = 'R U R'' U2'' R U R2'' F'' R U R U'' R'' F R U'' R'' U'' R U'' R''' WHERE code = 'Na-Perm';
UPDATE lib_cases SET scramble = 'F r'' F'' r U r U'' r2'' D'' F r U r'' F'' D r' WHERE code = 'Nb-Perm';
UPDATE lib_cases SET scramble = 'R U2'' R D R'' U R D'' R'' U'' R'' U R U R'' y''' WHERE code = 'Ra-Perm';
UPDATE lib_cases SET scramble = 'R'' U R U R'' U'' R'' D'' R U R'' D R U2'' R' WHERE code = 'Rb-Perm';
UPDATE lib_cases SET scramble = 'F R U'' R'' U R U R2'' F'' R U R U'' R''' WHERE code = 'T-Perm';
UPDATE lib_cases SET scramble = 'M2'' U'' M'' U2'' M U'' M2''' WHERE code = 'Ua-Perm';
UPDATE lib_cases SET scramble = 'M2'' U M'' U2'' M U M2''' WHERE code = 'Ub-Perm';
UPDATE lib_cases SET scramble = 'D2'' R'' U R D'' R2'' U'' R'' U R'' U R'' D'' R U2'' R''' WHERE code = 'V-Perm';
UPDATE lib_cases SET scramble = 'F R'' F'' R U R U'' R'' F R U'' R'' U R U R'' F''' WHERE code = 'Y-Perm';
UPDATE lib_cases SET scramble = 'M U2'' M2'' U2'' M U'' M2'' U'' M2''' WHERE code = 'Z-Perm';

COMMIT;
