-- Fix OELL setupSequence (scramble) values
-- The scramble values were incorrectly set to algorithms instead of setup moves
-- Generated by fix_oell_setup_sequences.py

BEGIN;

UPDATE lib_cases SET scramble = 'f U R U'' R'' f''' WHERE code = 'OeLL L';
UPDATE lib_cases SET scramble = 'F U R U'' R'' F''' WHERE code = 'OeLL Line';
UPDATE lib_cases SET scramble = 'f U R U'' R'' f'' F U R U'' R'' F''' WHERE code = 'OeLL Dot';

COMMIT;
