-- Fix OLL setupSequence (scramble) values
-- The scramble values were incorrectly set to algorithms instead of setup moves
-- Generated by fix_oll_setup_sequences.py

BEGIN;

UPDATE lib_cases SET scramble = 'F R'' F'' R U2'' F R'' F'' R2'' U2'' R''' WHERE code = 'OLL-1';
UPDATE lib_cases SET scramble = 'f U R U'' R'' f'' F U R U'' R'' F''' WHERE code = 'OLL-2';
UPDATE lib_cases SET scramble = 'F U R U'' R'' F'' U f U R U'' R'' f'' y' WHERE code = 'OLL-3';
UPDATE lib_cases SET scramble = 'F U R U'' R'' F'' U'' f U R U'' R'' f'' y' WHERE code = 'OLL-4';
UPDATE lib_cases SET scramble = 'r'' U'' R U'' R'' U2'' r' WHERE code = 'OLL-5';
UPDATE lib_cases SET scramble = 'r U R'' U R U2'' r''' WHERE code = 'OLL-6';
UPDATE lib_cases SET scramble = 'r U2'' R'' U'' R U'' r''' WHERE code = 'OLL-7';
UPDATE lib_cases SET scramble = 'r'' U2'' R U R'' U r y2''' WHERE code = 'OLL-8';
UPDATE lib_cases SET scramble = 'F U R U'' R2'' F'' R U R U'' R'' y''' WHERE code = 'OLL-9';
UPDATE lib_cases SET scramble = 'R U2'' R'' F R'' F'' R U'' R U'' R''' WHERE code = 'OLL-10';
UPDATE lib_cases SET scramble = 'M U'' R U2'' R'' U'' R U'' R2'' r' WHERE code = 'OLL-11';
UPDATE lib_cases SET scramble = 'F U R U'' R'' F'' U'' F U R U'' R'' F''' WHERE code = 'OLL-12';
UPDATE lib_cases SET scramble = 'F'' U'' F r U'' r'' U r U r''' WHERE code = 'OLL-13';
UPDATE lib_cases SET scramble = 'F U F'' R'' F R U'' R'' F'' R' WHERE code = 'OLL-14';
UPDATE lib_cases SET scramble = 'r'' U'' r U'' R'' U R r'' U r' WHERE code = 'OLL-15';
UPDATE lib_cases SET scramble = 'r U r'' U R U'' R'' r U'' r''' WHERE code = 'OLL-16';
UPDATE lib_cases SET scramble = 'F R'' F'' R U2'' F R'' F'' R U'' R U'' R''' WHERE code = 'OLL-17';
UPDATE lib_cases SET scramble = 'r'' U2'' R U R'' U r2'' U2'' R'' U'' R U'' r''' WHERE code = 'OLL-18';
UPDATE lib_cases SET scramble = 'F R'' F'' R M U R U'' R'' U'' M''' WHERE code = 'OLL-19';
UPDATE lib_cases SET scramble = 'r U R'' U'' M2'' U R U'' R'' U'' M''' WHERE code = 'OLL-20';
UPDATE lib_cases SET scramble = 'R U R'' U R U'' R'' U R U2'' R'' y''' WHERE code = 'OLL-21';
UPDATE lib_cases SET scramble = 'R'' U2'' R2'' U R2'' U R2'' U2'' R''' WHERE code = 'OLL-22';
UPDATE lib_cases SET scramble = 'R U2'' R D R'' U2'' R D'' R2''' WHERE code = 'OLL-23';
UPDATE lib_cases SET scramble = 'F R'' F'' r U R U'' r''' WHERE code = 'OLL-24';
UPDATE lib_cases SET scramble = 'R'' F'' r U R U'' r'' F y''' WHERE code = 'OLL-25';
UPDATE lib_cases SET scramble = 'R U R'' U R U2'' R'' y''' WHERE code = 'OLL-26';
UPDATE lib_cases SET scramble = 'R U2'' R'' U'' R U'' R''' WHERE code = 'OLL-27';
UPDATE lib_cases SET scramble = 'R U R'' U'' M'' U R U'' r''' WHERE code = 'OLL-28';
UPDATE lib_cases SET scramble = 'M F R'' F'' R U R U'' R'' U'' M''' WHERE code = 'OLL-29';
UPDATE lib_cases SET scramble = 'F U R U2'' R'' U R U2'' R'' U'' F'' y2''' WHERE code = 'OLL-30';
UPDATE lib_cases SET scramble = 'R'' F R U R'' U'' F'' U R' WHERE code = 'OLL-31';
UPDATE lib_cases SET scramble = 'f R'' F'' R U R U'' R'' S''' WHERE code = 'OLL-32';
UPDATE lib_cases SET scramble = 'F R'' F'' R U R U'' R''' WHERE code = 'OLL-33';
UPDATE lib_cases SET scramble = 'F U R'' U'' R'' F'' R U R2'' U'' R'' y2''' WHERE code = 'OLL-34';
UPDATE lib_cases SET scramble = 'R U2'' R'' F R'' F'' R2'' U2'' R''' WHERE code = 'OLL-35';
UPDATE lib_cases SET scramble = 'F'' L F L'' U'' L'' U'' L U L'' U L y2''' WHERE code = 'OLL-36';
UPDATE lib_cases SET scramble = 'F R U'' R'' U R U R'' F''' WHERE code = 'OLL-37';
UPDATE lib_cases SET scramble = 'F R'' F'' R U R U R'' U'' R U'' R''' WHERE code = 'OLL-38';
UPDATE lib_cases SET scramble = 'L U F'' U'' L'' U L F L'' y''' WHERE code = 'OLL-39';
UPDATE lib_cases SET scramble = 'R'' U'' F U R U'' R'' F'' R y''' WHERE code = 'OLL-40';
UPDATE lib_cases SET scramble = 'F U R U'' R'' F'' R U2'' R'' U'' R U'' R'' y2''' WHERE code = 'OLL-41';
UPDATE lib_cases SET scramble = 'F U R U'' R'' F'' R'' U2'' R U R'' U R' WHERE code = 'OLL-42';
UPDATE lib_cases SET scramble = 'f'' U'' L'' U L f' WHERE code = 'OLL-43';
UPDATE lib_cases SET scramble = 'f U R U'' R'' f''' WHERE code = 'OLL-44';
UPDATE lib_cases SET scramble = 'F U R U'' R'' F''' WHERE code = 'OLL-45';
UPDATE lib_cases SET scramble = 'R'' U'' F R'' F'' R U R' WHERE code = 'OLL-46';
UPDATE lib_cases SET scramble = 'F'' U'' L'' U L U'' L'' U L F' WHERE code = 'OLL-47';
UPDATE lib_cases SET scramble = 'F U R U'' R'' U R U'' R'' F''' WHERE code = 'OLL-48';
UPDATE lib_cases SET scramble = 'r'' U r2'' U'' r2'' U'' r2'' U r'' y2''' WHERE code = 'OLL-49';
UPDATE lib_cases SET scramble = 'r U'' r2'' U r2'' U r2'' U'' r' WHERE code = 'OLL-50';
UPDATE lib_cases SET scramble = 'f U R U'' R'' U R U'' R'' f''' WHERE code = 'OLL-51';
UPDATE lib_cases SET scramble = 'F R U R'' d R'' U'' R U'' R''' WHERE code = 'OLL-52';
UPDATE lib_cases SET scramble = 'r'' U2'' R U R'' U'' R U R'' U r' WHERE code = 'OLL-53';
UPDATE lib_cases SET scramble = 'r U2'' R'' U'' R U R'' U'' R U'' r''' WHERE code = 'OLL-54';
UPDATE lib_cases SET scramble = 'F R'' F'' U2'' R U R'' U R2'' U2'' R''' WHERE code = 'OLL-55';
UPDATE lib_cases SET scramble = 'r U r'' R U R'' U'' R U R'' U'' r U'' r''' WHERE code = 'OLL-56';
UPDATE lib_cases SET scramble = 'r U R'' U'' M U R U'' R''' WHERE code = 'OLL-57';

COMMIT;
