-- Fix PCLL setupSequence (scramble) values
-- The scramble values were incorrectly set to algorithms instead of setup moves
-- Generated by fix_pcll_setup_sequences.py

BEGIN;

UPDATE lib_cases SET scramble = 'R'' U L U'' R U L''' WHERE code = 'PcLL Adjacent';
UPDATE lib_cases SET scramble = 'F R'' F'' R U R U'' R'' F'' R U'' R U R'' U R'' F' WHERE code = 'PcLL Diagonal';

COMMIT;
